package net.chrisdolan.pcgen.drools.pathfinder;
    dialect "java"

import net.chrisdolan.pcgen.drools.test.*;
import net.chrisdolan.pcgen.drools.input.*;
import net.chrisdolan.pcgen.drools.type.*;

rule "Test.TestInput"
    when
        TestInput($t:type, $st:subtype, $v:value)
    then
        insertLogical(new Input($t, $st, $v));
end
rule "Test.TestInput.Size"
    when
        SpecialTestInput(type == "Size", $st:subtype, $v:value)
    then
        insertLogical(new Size($st));
end

rule "Typo.ClassSkill"
    when
        $o : ClassSkill($classname:classname,$skill:name)
        (not ClassName($classname == name) or not SkillType(name == $skill))
    then
        throw new Exception(""+$o);
end
rule "Typo.MaxClassLevel"
    when
        $o : MaxClassLevel($classname:classname)
        not ClassName($classname == name)
    then
        throw new Exception(""+$o);
end
rule "Typo.HitDie"
    when
        $o : HitDie($classname:classname)
        not ClassName($classname == name)
    then
        throw new Exception(""+$o);
end
rule "Typo.BABProgression"
    when
        $o : BABProgression($classname:classname)
        not ClassName($classname == name)
    then
        throw new Exception(""+$o);
end
rule "Typo.SaveProgression"
    when
        $o : SaveProgression($classname:classname)
        not ClassName($classname == name)
    then
        throw new Exception(""+$o);
end
