package net.chrisdolan.pcgen.drools.pathfinder;
    dialect "java"

import net.chrisdolan.pcgen.drools.input.*;
import net.chrisdolan.pcgen.drools.type.*;

rule "Class.Fighter.Init"
    salience 1000
    when
    then
        insertLogical(new ClassName("Fighter"));
        insertLogical(new MaxClassLevel("Fighter", 20));
        insertLogical(new HitDie("Fighter", 10));
        insertLogical(new BABProgression("Fighter", "Fast"));
        insertLogical(new SaveProgression("Fighter", SavingThrow.FORT, "Fast"));
        insertLogical(new SaveProgression("Fighter", SavingThrow.REFL, "Slow"));
        insertLogical(new SaveProgression("Fighter", SavingThrow.WILL, "Slow"));
        insertLogical(new SkillPointsPerLevel("Fighter", 2));
end
rule "Class.Fighter.ClassSkill.Init"
    salience 1000
    when
        not ClassSkillOverride(classname == "Fighter")
    then
        insertLogical(new ClassSkill("Fighter", "Climb"));
        insertLogical(new ClassSkill("Fighter", "Craft"));
        insertLogical(new ClassSkill("Fighter", "HandleAnimal"));
        insertLogical(new ClassSkill("Fighter", "Intimidate"));
        insertLogical(new ClassSkill("Fighter", "Knowledge.Dungeoneering"));
        insertLogical(new ClassSkill("Fighter", "Knowledge.Engineering"));
        insertLogical(new ClassSkill("Fighter", "Profession"));
        insertLogical(new ClassSkill("Fighter", "Ride"));
        insertLogical(new ClassSkill("Fighter", "Survival"));
        insertLogical(new ClassSkill("Fighter", "Swim"));
end
