package net.chrisdolan.pcgen.drools.pathfinder;
    dialect "java"

import net.chrisdolan.pcgen.drools.input.*;
import net.chrisdolan.pcgen.drools.type.*;

rule "Class.Druid.Init"
    salience 1000
    when
    then
        insertLogical(new ClassName("Druid"));
        insertLogical(new MaxClassLevel("Druid", 20));
        insertLogical(new HitDie("Druid", 8));
        insertLogical(new BABProgression("Druid", "Medium"));
        insertLogical(new SaveProgression("Druid", SavingThrow.FORT, "Fast"));
        insertLogical(new SaveProgression("Druid", SavingThrow.REFL, "Slow"));
        insertLogical(new SaveProgression("Druid", SavingThrow.WILL, "Fast"));
end
