package net.chrisdolan.pcgen.drools.pathfinder;
    dialect "java"

import net.chrisdolan.pcgen.drools.input.*;
import net.chrisdolan.pcgen.drools.type.*;

rule "Class.Cleric.Init"
    salience 1000
    when
    then
        insertLogical(new ClassName("Cleric"));
        insertLogical(new MaxClassLevel("Cleric", 20));
        insertLogical(new HitDie("Cleric", 8));
        insertLogical(new BABProgression("Cleric", "Medium"));
        insertLogical(new SaveProgression("Cleric", SavingThrow.FORT, "Fast"));
        insertLogical(new SaveProgression("Cleric", SavingThrow.REFL, "Slow"));
        insertLogical(new SaveProgression("Cleric", SavingThrow.WILL, "Fast"));
        insertLogical(new SkillPointsPerLevel("Cleric", 2));
end
rule "Class.Cleric.ClassSkill.Init"
    salience 1000
    when
        not ClassSkillOverride(classname == "Cleric")
    then
        insertLogical(new ClassSkill("Cleric", "Appraise"));
        insertLogical(new ClassSkill("Cleric", "Craft"));
        insertLogical(new ClassSkill("Cleric", "Diplomacy"));
        insertLogical(new ClassSkill("Cleric", "Heal"));
        insertLogical(new ClassSkill("Cleric", "Knowledge.Arcana"));
        insertLogical(new ClassSkill("Cleric", "Knowledge.History"));
        insertLogical(new ClassSkill("Cleric", "Knowledge.Nobility"));
        insertLogical(new ClassSkill("Cleric", "Knowledge.Planes"));
        insertLogical(new ClassSkill("Cleric", "Knowledge.Religion"));
        insertLogical(new ClassSkill("Cleric", "Linguistics"));
        insertLogical(new ClassSkill("Cleric", "Profession"));
        insertLogical(new ClassSkill("Cleric", "SenseMotive"));
        insertLogical(new ClassSkill("Cleric", "Spellcraft"));
end
