package net.chrisdolan.pcgen.drools.pathfinder;
    dialect "java"

import net.chrisdolan.pcgen.drools.input.*;
import net.chrisdolan.pcgen.drools.type.*;

rule "Class.Sorcerer.Init"
    salience 1000
    when
    then
        insertLogical(new ClassName("Sorcerer"));
        insertLogical(new MaxClassLevel("Sorcerer", 20));
        insertLogical(new HitDie("Sorcerer", 6));
        insertLogical(new BABProgression("Sorcerer", "Slow"));
        insertLogical(new SaveProgression("Sorcerer", SavingThrow.FORT, "Slow"));
        insertLogical(new SaveProgression("Sorcerer", SavingThrow.REFL, "Slow"));
        insertLogical(new SaveProgression("Sorcerer", SavingThrow.WILL, "Fast"));
end
