package net.chrisdolan.pcgen.drools.pathfinder;
    dialect "java"

import net.chrisdolan.pcgen.drools.input.*;
import net.chrisdolan.pcgen.drools.type.*;

rule "Class.Barbarian.Init"
    salience 1000
    when
    then
        insertLogical(new ClassName("Barbarian"));
        insertLogical(new MaxClassLevel("Barbarian", 20));
        insertLogical(new HitDie("Barbarian", 12));
        insertLogical(new BABProgression("Barbarian", "Fast"));
        insertLogical(new SaveProgression("Barbarian", SavingThrow.FORT, "Fast"));
        insertLogical(new SaveProgression("Barbarian", SavingThrow.REFL, "Slow"));
        insertLogical(new SaveProgression("Barbarian", SavingThrow.WILL, "Slow"));
end
rule "Class.Barbarian.ClassSkill.Init"
    salience 1000
    when
        not ClassSkillOverride(classname == "Barbarian")
    then
        insertLogical(new ClassSkill("Barbarian", "Acrobatics"));
        insertLogical(new ClassSkill("Barbarian", "Climb"));
        insertLogical(new ClassSkill("Barbarian", "Craft"));
        insertLogical(new ClassSkill("Barbarian", "HandleAnimal"));
        insertLogical(new ClassSkill("Barbarian", "Intimidate"));
        insertLogical(new ClassSkill("Barbarian", "Knowledge.Nature"));
        insertLogical(new ClassSkill("Barbarian", "Perception"));
        insertLogical(new ClassSkill("Barbarian", "Ride"));
        insertLogical(new ClassSkill("Barbarian", "Survival"));
        insertLogical(new ClassSkill("Barbarian", "Swim"));
end

rule "Class.Barbarian.Rage"
    when
        Condition(type == ConditionInput.TYPE_RAGE)
        Input(type == "ClassLevel", subtype == "Barbarian", $lvl:value) // temporary. Replace with greater/mighty rage ability to allow archetype overrides
    then
        insertLogical(new Input(StatInput.TYPE + StatInput.STR, "Morale", $lvl >= 20 ? 8 : $lvl >= 11 ? 6 : 4));
        insertLogical(new Input(StatInput.TYPE + StatInput.CON, "Morale", $lvl >= 20 ? 8 : $lvl >= 11 ? 6 : 4));
        insertLogical(new Input(SavingThrow.TYPE + SavingThrow.WILL, "Morale", $lvl >= 20 ? 4 : $lvl >= 11 ? 3 : 2));
        insertLogical(new Input(ArmorClass.TYPE, "Rage", -2));
        // todo: greater/mighty rage
end  