package net.chrisdolan.pcgen.drools.pathfinder;
    dialect "java"

import net.chrisdolan.pcgen.drools.input.*;
import net.chrisdolan.pcgen.drools.type.*;

rule "Class.Druid.Init"
    salience 1000
    when
    then
        insertLogical(new ClassName("Druid"));
        insertLogical(new MaxClassLevel("Druid", 20));
        insertLogical(new HitDie("Druid", 8));
        insertLogical(new BABProgression("Druid", "Medium"));
        insertLogical(new SaveProgression("Druid", SavingThrow.FORT, "Fast"));
        insertLogical(new SaveProgression("Druid", SavingThrow.REFL, "Slow"));
        insertLogical(new SaveProgression("Druid", SavingThrow.WILL, "Fast"));
        insertLogical(new SkillPointsPerLevel("Druid", 4));
        insertLogical(new SpellCasterClass("Druid"));
end
rule "Class.Druid.ClassSkill.Init"
    salience 1000
    when
        not ClassSkillOverride(classname == "Druid")
    then
        insertLogical(new ClassSkill("Druid", "Climb"));
        insertLogical(new ClassSkill("Druid", "Craft"));
        insertLogical(new ClassSkill("Druid", "Diplomacy"));
        insertLogical(new ClassSkill("Druid", "Fly"));
        insertLogical(new ClassSkill("Druid", "HandleAnimal"));
        insertLogical(new ClassSkill("Druid", "Heal"));
        insertLogical(new ClassSkill("Druid", "Knowledge.Geography"));
        insertLogical(new ClassSkill("Druid", "Knowledge.Nature"));
        insertLogical(new ClassSkill("Druid", "Perception"));
        insertLogical(new ClassSkill("Druid", "Profession"));
        insertLogical(new ClassSkill("Druid", "Ride"));
        insertLogical(new ClassSkill("Druid", "Spellcraft"));
        insertLogical(new ClassSkill("Druid", "Survival"));
        insertLogical(new ClassSkill("Druid", "Swim"));
end
