package net.chrisdolan.pcgen.drools.pathfinder;
    dialect "java"

import net.chrisdolan.pcgen.drools.input.*;
import net.chrisdolan.pcgen.drools.type.*;

rule "Class.Sorcerer.Init"
    salience 1000
    when
    then
        insertLogical(new ClassName("Sorcerer"));
        insertLogical(new MaxClassLevel("Sorcerer", 20));
        insertLogical(new HitDie("Sorcerer", 6));
        insertLogical(new BABProgression("Sorcerer", "Slow"));
        insertLogical(new SaveProgression("Sorcerer", SavingThrow.FORT, "Slow"));
        insertLogical(new SaveProgression("Sorcerer", SavingThrow.REFL, "Slow"));
        insertLogical(new SaveProgression("Sorcerer", SavingThrow.WILL, "Fast"));
        insertLogical(new SkillPointsPerLevel("Sorcerer", 2));
end
rule "Class.Sorcerer.ClassSkill.Init"
    salience 1000
    when
        not ClassSkillOverride(classname == "Sorcerer")
    then
        insertLogical(new ClassSkill("Sorcerer", "Appraise"));
        insertLogical(new ClassSkill("Sorcerer", "Bluff"));
        insertLogical(new ClassSkill("Sorcerer", "Craft"));
        insertLogical(new ClassSkill("Sorcerer", "Fly"));
        insertLogical(new ClassSkill("Sorcerer", "Intimidate"));
        insertLogical(new ClassSkill("Sorcerer", "Knowledge.Arcana"));
        insertLogical(new ClassSkill("Sorcerer", "Profession"));
        insertLogical(new ClassSkill("Sorcerer", "Spellcraft"));
        insertLogical(new ClassSkill("Sorcerer", "UseMagicDevice"));
end
