package net.chrisdolan.pcgen.drools.pathfinder;
    dialect "java"

import net.chrisdolan.pcgen.drools.input.*;
import net.chrisdolan.pcgen.drools.type.*;

rule "Class.Wizard.Init"
    salience 1000
    when
    then
        insertLogical(new ClassName("Wizard"));
        insertLogical(new MaxClassLevel("Wizard", 20));
        insertLogical(new HitDie("Wizard", 6));
        insertLogical(new BABProgression("Wizard", "Slow"));
        insertLogical(new SaveProgression("Wizard", SavingThrow.FORT, "Slow"));
        insertLogical(new SaveProgression("Wizard", SavingThrow.REFL, "Slow"));
        insertLogical(new SaveProgression("Wizard", SavingThrow.WILL, "Fast"));
        insertLogical(new SkillPointsPerLevel("Wizard", 2));
end
rule "Class.Wizard.ClassSkill.Init"
    salience 1000
    when
        not ClassSkillOverride(classname == "Wizard")
    then
        insertLogical(new ClassSkill("Wizard", "Appraise"));
        insertLogical(new ClassSkill("Wizard", "Craft"));
        insertLogical(new ClassSkill("Wizard", "Fly"));
        insertLogical(new ClassSkill("Wizard", "Knowledge.Arcana"));
        insertLogical(new ClassSkill("Wizard", "Knowledge.Dungeoneering"));
        insertLogical(new ClassSkill("Wizard", "Knowledge.Engineering"));
        insertLogical(new ClassSkill("Wizard", "Knowledge.Geography"));
        insertLogical(new ClassSkill("Wizard", "Knowledge.History"));
        insertLogical(new ClassSkill("Wizard", "Knowledge.Local"));
        insertLogical(new ClassSkill("Wizard", "Knowledge.Nature"));
        insertLogical(new ClassSkill("Wizard", "Knowledge.Nobility"));
        insertLogical(new ClassSkill("Wizard", "Knowledge.Planes"));
        insertLogical(new ClassSkill("Wizard", "Knowledge.Religion"));
        insertLogical(new ClassSkill("Wizard", "Linguistics"));
        insertLogical(new ClassSkill("Wizard", "Profession"));
        insertLogical(new ClassSkill("Wizard", "Spellcraft"));
end
