package net.chrisdolan.pcgen.drools.pathfinder;
    dialect "java"

import net.chrisdolan.pcgen.drools.input.*;
import net.chrisdolan.pcgen.drools.type.*;

rule "Class.Rogue.Init"
    salience 1000
    when
    then
        insertLogical(new ClassName("Rogue"));
        insertLogical(new MaxClassLevel("Rogue", 20));
        insertLogical(new HitDie("Rogue", 8));
        insertLogical(new BABProgression("Rogue", "Medium"));
        insertLogical(new SaveProgression("Rogue", SavingThrow.FORT, "Slow"));
        insertLogical(new SaveProgression("Rogue", SavingThrow.REFL, "Fast"));
        insertLogical(new SaveProgression("Rogue", SavingThrow.WILL, "Slow"));
end
