package net.chrisdolan.pcgen.drools.pathfinder;
    dialect "java"

import net.chrisdolan.pcgen.drools.input.*;
import net.chrisdolan.pcgen.drools.type.*;

query "Query.FavoredClass.All"
    FavoredClass(name : name)
end

declare FavoredClass
    name : String
end

rule "FavoredClass.UserInput"
    when
        FavoredClassInput($c:name)
    then
        insertLogical(new FavoredClass($c));
end


rule "Validation.FavoredClass.Missing"
    when
        Race()
        not FavoredClassInput()
    then
        insertLogical(new MissingInputViolation("FavoredClass.Missing", "Please choose a favored class", null));
end
