package net.chrisdolan.pcgen.drools;
    dialect "java"

import net.chrisdolan.pcgen.drools.input.*;
import net.chrisdolan.pcgen.drools.type.*;

rule "PC.UserInput"
    salience 100
    when
        $pc:PCInput()
    then
        for (PropertyInput p : $pc.getProperties())
             insertLogical(p);
        if ($pc.getAlignment() != null)
            insertLogical($pc.getAlignment());
        for (StatInput stat : $pc.getStats())
             insertLogical(stat);
        if ($pc.getRace() != null)
            insertLogical($pc.getRace());
        for (LevelInput lvl : $pc.getLevels())
             insertLogical(lvl);
        if ($pc.getInventory() != null)
            insertLogical($pc.getInventory());

        for (ConditionInput condition : $pc.getConditions())
             insertLogical(condition);
        for (DamageInput damage : $pc.getDamage())
             insertLogical(damage);
        for (ActionInput action : $pc.getActions())
             insertLogical(action);
end

rule "PC.Level.UserInput"
    salience 99
    when
        $lvl:LevelInput()
    then
        for (ArchetypeInput archetype : $lvl.getArchetypes())
             insertLogical(archetype);
        if ($lvl.getHitpoints() != null)
            insertLogical($lvl.getHitpoints());
        for (SkillInput skill : $lvl.getSkills())
             insertLogical(skill);
        if ($lvl.getFavoredClassBonus() != null)
             insertLogical($lvl.getFavoredClassBonus());
        for (FeatInput feat : $lvl.getFeats())
             insertLogical(feat);
end
