package net.chrisdolan.pcgen.drools;
    dialect "java"

import net.chrisdolan.pcgen.drools.input.*;
import net.chrisdolan.pcgen.drools.type.*;

declare Size
    type : String
end

rule "Size.Colossal"
    when
        Size(type == "Colossal")
    then
        insertLogical(new Input(ArmorClass.TYPE, ArmorClass.SUBTYPE_SIZE, -8));
        insertLogical(new Input("CMB", "Size", 8));
        insertLogical(new Input("CMD", "Size", 8));
end
rule "Size.Gargantuan"
    when
        Size(type == "Gargantuan")
    then
        insertLogical(new Input(ArmorClass.TYPE, ArmorClass.SUBTYPE_SIZE, -4));
        insertLogical(new Input("CMB", "Size", 4));
        insertLogical(new Input("CMD", "Size", 4));
end
rule "Size.Huge"
    when
        Size(type == "Huge")
    then
        insertLogical(new Input(ArmorClass.TYPE, ArmorClass.SUBTYPE_SIZE, -2));
        insertLogical(new Input("CMB", "Size", 2));
        insertLogical(new Input("CMD", "Size", 2));
end
rule "Size.Large"
    when
        Size(type == "Large")
    then
        insertLogical(new Input(ArmorClass.TYPE, ArmorClass.SUBTYPE_SIZE, -1));
        insertLogical(new Input("CMB", "Size", 1));
        insertLogical(new Input("CMD", "Size", 1));
end
rule "Size.Small"
    when
        Size(type == "Small")
    then
        insertLogical(new Input(ArmorClass.TYPE, ArmorClass.SUBTYPE_SIZE, 1));
        insertLogical(new Input("CMB", "Size", -1));
        insertLogical(new Input("CMD", "Size", -1));
end
rule "Size.Tiny"
    when
        Size(type == "Tiny")
    then
        insertLogical(new Input(ArmorClass.TYPE, ArmorClass.SUBTYPE_SIZE, 2));
        insertLogical(new Input("CMB", "Size", -2));
        insertLogical(new Input("CMD", "Size", -2));
end
rule "Size.Diminutive"
    when
        Size(type == "Diminutive")
    then
        insertLogical(new Input(ArmorClass.TYPE, ArmorClass.SUBTYPE_SIZE, 4));
        insertLogical(new Input("CMB", "Size", -4));
        insertLogical(new Input("CMD", "Size", -4));
end
rule "Size.Fine"
    when
        Size(type == "Fine")
    then
        insertLogical(new Input(ArmorClass.TYPE, ArmorClass.SUBTYPE_SIZE, 8));
        insertLogical(new Input("CMB", "Size", -8));
        insertLogical(new Input("CMD", "Size", -8));
end
