package net.chrisdolan.pcgen.drools.pathfinder;
    dialect "java"

import net.chrisdolan.pcgen.drools.input.*;
import net.chrisdolan.pcgen.drools.type.*;

query "Query.Violations"
    violation : Violation()
end
query "Query.Violations.Descriptions"
    Violation(violation : description)
end
query "Query.Violations.Codes"
    Violation(violation : code)
end
query "Query.Violations.MissingInputs"
    violation : MissingInputViolation()
end

declare Violation
    code : String
    description : String
end
declare InvalidInputViolation extends Violation
    violators : Object[]
end
declare MissingInputViolation extends Violation
    defaultvalue : Object
end
declare MissingPrereqViolation extends Violation
    violators : Object[]
end
declare ExcessInputViolation extends Violation
    violators : Object[]
end
declare ConflictViolation extends Violation
    violators : Object[]
end
